# Generated by Django 4.1.4 on 2023-01-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='dex',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
