# Generated by Django 4.1.4 on 2023-01-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_dex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('identifier', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='dex',
            new_name='identifier',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='type',
            field=models.ManyToManyField(to='pokedex.type'),
        ),
    ]
