# Generated by Django 4.1.4 on 2023-01-19 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_type_rename_dex_pokemon_identifier_pokemon_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='type',
            new_name='types',
        ),
    ]
