# Generated by Django 4.1.4 on 2023-02-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokedex", "0004_rename_type_pokemon_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pokemon",
            old_name="types",
            new_name="type",
        ),
        migrations.AlterField(
            model_name="pokemon",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
